### PR TITLE
Update samples from Release-169 as a part of 1.50.0 SDK stable release

### PR DESCRIPTION
**Pull request by skasturi**
@sarthaks95

### CODE REVIEW

**Comment by skasturi** [comment]
#signoff

Signing off as Nikhil does not have access.

**Comment by skasturi** [comment]
#sign-off

**Review by v-vvogir — APPROVED** [review]

**Comment by singankit** [comment]
#sign-off

**Comment by paulshealy1** [comment]
#sign-off

**Review by jeff-shepherd — APPROVED** [review]

**Comment by jeff-shepherd** [comment]
#sign-off

**Comment by v-vvogir** [comment]
#sign-off

**Review by vizhur — APPROVED** [review]

**Pull request merged**
