### PR TITLE
AutoML README.md simplified

### PR DESCRIPTION
**Pull request by CESARDELATORRE**
AutoML README.md simplified.
AML 'Compute Instance' should be the by default way to go.
Local Conda installation is now in a segregated page so it doesn't make the home README.md so complex.

### CODE REVIEW

**Comment by CESARDELATORRE** [comment]
@Aniththa , can you review and approve/merge, please?

**Comment by Aniththa** [comment]
#sign-off

**Comment by CESARDELATORRE** [comment]
@Aniththa  It looks you still didn't approved the PR?

**Comment by lostmygithubaccount** [comment]
@CESARDELATORRE @Aniththa is this still relevant? can you close it if not?

**Comment by CESARDELATORRE** [comment]
Closing this since it's stale.

**Pull request closed without merging**
